version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - DEBUG=False
      - PORT=8000
      - HOST=0.0.0.0
      - DEFAULT_CITY=Paris
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    restart: unless-stopped

  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    environment:
      - DEBUG=True
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=''
      --NotebookApp.password=''