version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=evacuation_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: